### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by snpdzk** [RaphiMC/ViaBedrock#23]
![image](https://github.com/RaphiMC/ViaBedrock/assets/130619899/eb8ecad2-06e4-41de-a5cf-de2f2ca89ccd)
[01:24:52] [Render thread/INFO]: Connecting to 127.0.0.1, 19132
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: 127.0.0.1/127.0.0.1:19132
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: Caused by: java.net.ConnectException: Connection refused: no further information
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:24:52] [Netty Client IO #8/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[01:24:52] [Netty Client IO #8/WARN]: Received packet INVENTORY_SLOT before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/WARN]: Received packet INVENTORY_SLOT before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/WARN]: Received packet INVENTORY_SLOT before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/WARN]: Received packet INVENTORY_SLOT before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/WARN]: Received packet PLAYER_LIST before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/WARN]: Received packet SET_TIME before START_GAME packet. Ignoring it.
[01:24:52] [Netty Client IO #8/INFO]: Server feature version: *
[01:24:52] [Netty Client IO #8/WARN]: This server uses server authoritative movement. This is not stable yet.
[01:24:52] [Render thread/INFO]: New minimap session initialized!
[01:24:52] [Render thread/INFO]: New world map session initialized!
[01:24:52] [Render thread/INFO]: Started 10 worker threads
[01:24:52] [Render thread/INFO]: Using 3 total BufferBuilder caches
[01:24:52] [Render thread/INFO]: Stopping worker threads
[01:24:52] [Render thread/INFO]: Started 10 worker threads
[01:24:52] [Render thread/INFO]: Stopping worker threads
[01:24:52] [Render thread/INFO]: Started 10 worker threads

**Comment by RaphiMC** [comment]
I need more details. What client version, what server version and software

**Comment by snpdzk** [comment]
version 1.19.4,server version 1.19.80.02

**Comment by RaphiMC** [comment]
1.19.80.02 is not longer supported. Please update ViaBedrock

**Comment by RaphiMC** [comment]
Closed due to inactivity
